### PR TITLE
TST: Limit the timer report to just the 15 longest tests

### PR DESCRIPTION
**Pull request by richafrank**
The default of all the tests is pretty spammy.

### CODE REVIEW

**Comment by ssanderson** [comment]
@llllllllll @richafrank I added this change directly to `setup.cfg` in my speedup-retrieve-all branch so that it also becomes the default for devs.

**Comment by llllllllll** [comment]
Looks like you have `timer-filter=warning`. Also, this is added to the setup.cfg here too

**Comment by ssanderson** [comment]
Oh, actually, I made a slightly different change in my branch: I made it only show tests that were in the `warning` threshold for speed.  Anythoughts on the difference?

**Comment by ssanderson** [comment]
@llllllllll yeah, I thought I had done top-n, but I actually did the threshold.  Any preference between the two?  I'm rebasing a conflict here now.

**Comment by richafrank** [comment]
How much output do we get with just `warning`?

**Comment by ssanderson** [comment]
@richafrank running now to see.

**Pull request merged**
