### PR TITLE
Position tracker serialization

### PR DESCRIPTION
**Pull request by dalejung**
After slogging through the reflocs, found the commits. Refactored Position management out of the PerformancePeriods since the logic was being duplicated. Also added pickle methods for each PerformanceTracker, PerformancePeriod, Postion, PositionTracker.

Also, I hate git.

### CODE REVIEW

**Comment by dalejung** [comment]
@CaptainKanuk here was the zipline PR

**Comment by CaptainKanuk** [comment]
Thanks. At this point I'm going to trust that your changes make sense here and focus on the other objects not touched here.

**Comment by dalejung** [comment]
big mistake! once I can rebase the qexec stuff, the integrations tests will green/redlight it anyways.

**Comment by dalejung** [comment]
Will need to rebase and refactor once https://github.com/quantopian/zipline/pull/510 is merged.

**Comment by dalejung** [comment]
mm, this is turning out to be a bear to rebase, i'm just gonna manually port it over.

**Pull request closed without merging**
