### PR TITLE
ENH: Take open market orders into account when constructing a new ord…

### PR DESCRIPTION
**Pull request by StewartDouglas**
…er target

Currently writing tests.

DO NOT MERGE.

@jfkirk @dunster @fawce @adeychman @ssanderson for awareness

### CODE REVIEW

**Comment by StewartDouglas** [comment]
Test case added

**Comment by twiecki** [comment]
While we're changing the order logic, could we try to wrap these very useful changes in as well: https://github.com/quantopian/zipline/pull/477?

**Comment by StewartDouglas** [comment]
@twiecki we're going to hold off merging this at the current time. We've been discussing an alternative, and more general solution related to what @ssanderson is working on.

**Comment by ssanderson** [comment]
Closing this as stale.

**Pull request closed without merging**
