### PR TITLE
fix issue #119 :Add an option to turn off benchmark/treasury updating

### PR DESCRIPTION
**Pull request by florentchandelier**
Issue: So that Zipline can be run offline, i.e. so that a downloaded dataset can be used when there is no internet connection. Without the option to disable benchmarks Zipline will currently crash on a socket exception while calling data.loader.update_benchmarks

Proposed Solution: Simply check for a connection status, and if no connection bypassing the update_benchmark() in loader.py, and use the data previously cached in ./zipline/data/\* for benchmark and treasuries, and ./zipline/cache/\* for stocks ... thus as if the connection was live.

### CODE REVIEW

**Comment by ssanderson** [comment]
@florentchandelier I'll take a look at this soon.  Sorry for the radio silence.

**Comment by ssanderson** [comment]
@florentchandelier I'm not sure how robust checking against google will be.  How would you feel about just adding a `nodownload` flag to `load_market_data` so that you could explicitly say not to query remote data?  Another variation on this would be to check for an environment variable like `ZIPLINE_DISABLE_NETWORK` or somesuch and check that before attempting to download.

**Comment by florentchandelier** [comment]
Considering this relates only to beeing able to dl data, and more specifically to have an internet connection, I fell this must not have any impact on a written code, and thus I would advise against using a flag.

I agree checking against google is not elegant. Maybe a cleaner way would be an appropriate try/error catch ? This would be transparent for the end programmer when backtesting, and I believe this should be the objective here.

Thus, I would advocate for a clean implementation of an environment variable, as you suggested, yet performed automatically by the system.

If you could point me to where this should sit in the code, I could try to code such approach.

**Comment by ssanderson** [comment]
@florentchandelier there are now two places in `ensure_benchmark_data` and `ensure_treasury_data` where the logic looks like:

```
        data = pd.Series.from_csv(path).tz_localize('UTC')
        if has_data_for_dates(data, first_date, last_date):
            return data
```

If you wanted to allow and environment-variable-based short-circuit, that logic should probably become something like:

```
        data = pd.Series.from_csv(path).tz_localize('UTC')
        if os.environ.get("ZIPLINE_NO_REMOTE_DATA"):
            logger.info(
                "Using cached data because ZIPLINE_NO_REMOTE_DATA was set."
            )
            return data
        if has_data_for_dates(data, first_date, last_date):
            return data
```

**Comment by ssanderson** [comment]
FYI, I recently rewrote the benchmark/treasury loader pretty thoroughly.  It should be on the order of 5 to 10x faster now.

**Comment by llllllllll** [comment]
@florentchandelier still working on this or should we close this for now?

**Comment by florentchandelier** [comment]
Thx for popping this out again. Was definitely not on my agenda anymore, kindly let me have a look at it over the next few weeks, until late february. Thanks.

**Comment by florentchandelier** [comment]
I'm finalizing some simple code that consolidates all .csv file in .zipline/cache directory and further pass properly formatted data to algo.run(). I have to complete same for teasuries/benchmark.

With the previous, I have to check if that all makes sense considering the original issue (mostly around benchmark).

That should be finished within the next few days/weeks.

**Comment by florentchandelier** [comment]
Hi there, 
I think this issue could be closed but marked as unresolved. I have indeed decide to move forward with a more traditional: unlike my original objective that was for zipline to automatically detect whether or not it is online, the burden is on the user side to either load locally files, or use internet to fetch data if an internet connection is available..

I will thus keep working on a data loader and consolidator that eventually check if data to be used for backtesting could be harvested from the zipline/cache directory by default.

I have currently commited this but more is to come: https://github.com/florentchandelier/zipline2quantopian/blob/f11360241dbabf333e114bd719e46cbf95008079/skeleton/generic_modules/custom_data.py

**Comment by freddiev4** [comment]
Going to close this considering the most recent comment, as well as that there are some other PRs that address this in different ways.

**Pull request closed without merging**
