### PR TITLE
Replace FastSeries with cython ordereddict

### PR DESCRIPTION
**Pull request by dalejung**

### CODE REVIEW

**Comment by dalejung** [comment]
hello bots

**Comment by dalejung** [comment]
i am the Singularity.

**Comment by twiecki** [comment]
Any perf numbers to go with that?

**Comment by ehebert** [comment]
@twiecki I'll get some numbers this morning.

**Comment by ehebert** [comment]
@twieck it's about 15% faster on algorithm that uses 16 stocks and holds a
position on each one.
And about 30% faster on an algorithm uses 160 and holds a position on each
one.

**Comment by twiecki** [comment]
Wow!

On Fri, Feb 20, 2015 at 6:10 PM, Eddie Hebert <notifications@github.com>
wrote:

> @twieck it's about 15% faster on algorithm that uses 16 stocks and holds a
> position on each one.
> And about 30% faster on an algorithm uses 160 and holds a position on each
> one.
>
> On Fri, Feb 20, 2015 at 7:49 AM, Eddie Hebert <ehebert@quantopian.com>
> wrote:
>
>
> > @twiecki I'll get some numbers this morning.
> > On Feb 20, 2015 3:35 AM, "Thomas Wiecki" <notifications@github.com>
> wrote:
> >
> >> Any perf numbers to go with that?
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/quantopian/zipline/pull/497#issuecomment-75205242>.
> >>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/quantopian/zipline/pull/497#issuecomment-75277411>.
>



-- 
Thomas Wiecki, PhD
Data Science Lead, Quantopian Inc, Boston

**Comment by dalejung** [comment]
already merged

**Pull request closed without merging**
