### PR TITLE
Setup.py improvements

### PR DESCRIPTION
**Pull request by jikamens**
Make "python setup.py install" actually work.

### CODE REVIEW

**Comment by jikamens** [comment]
@twiecki can you take a look at this and let me know if I did anything stupid?

**Comment by jikamens** [comment]
This was prompted by the email last night to the zipline mailing list about installing the package not working properly.

**Comment by ssanderson** [comment]
@jikamens I think there's a fair amount of overlap between this and https://github.com/quantopian/zipline/pull/678/.

**Comment by dkossack** [comment]
`conda build zipline` worked with the following changes to setup.py:

Source:
  git_url: https://github.com/quantopian/zipline.git
  git_tag: setup_py_improvements

Build needed: 
  numpy
Run needed:
  contextlib2
  numexpr
  networkx

diff meta.yaml meta.yaml.bak:
6,7c6,8
\<   git_url: https://github.com/quantopian/zipline.git
\<   git_tag: setup_py_improvements
\---
\>   fn: zipline-0.8.0rc1.tar.gz
\>   url: https://pypi.python.org/packages/source/z/zipline/zipline-0.8.0rc1.tar.gz
\>   md5: f23bdd0a8671b3b297072391fc817097
13d13
\<     - numpy
24,26d23
\<     - contextlib2
\<     - numexpr
\<     - networkx

zipline/examples/dual_moving_average.py worked without issue.
The 'examples' directory was not installed with zipline.
Thanks...

**Comment by ssanderson** [comment]
I'm looking at merging the lazy-Cythonization and `find_packages` changes into my branch that generates `install_requires` from our requirements.txt.

**Comment by jikamens** [comment]
>@jikamens I think there's a fair amount of overlap between this and #678

This is #678, so not clear what you meant to refer to here.

>I'm looking at merging the lazy-Cythonization and find_packages changes here into my branch that generates install_requires from our requirements.txt.

:+1: but please keep my name on the commits kthnxbye.

**Comment by twiecki** [comment]
@jikamens Looks good to me. The alternative is to include the `.c` files in the packaged version (http://docs.cython.org/src/reference/compilation.html#distributing-cython-modules). Since we also don't peg the Cython version here this might cause some issues with version incompatibilities.

**Comment by llllllllll** [comment]
@jikamens @ssanderson What is the status of this, I need a solution so that we can deploy zipline on the databazaar box.

**Comment by jikamens** [comment]
Closing in favor of #681

**Pull request closed without merging**
