### PR TITLE
ENH: An improved error message when calling zipline api functions

### PR DESCRIPTION
**Pull request by richafrank**
outside of a running simulation. Previously, an AttributeError was
raised.

The goal here is to make the situation clearer for developers, for example: https://github.com/quantopian/zipline/issues/1541 and https://github.com/quantopian/zipline/issues/448#issuecomment-249312347

What do folks think of the message?

### CODE REVIEW

**Comment by ssanderson** [comment]
:+1: from me

**Comment by ssanderson** [comment]
The only change I could maybe see here is adding a specific exception type for this (e.g. `NoSimulationRunning`) rather than `RuntimeError`.  But I don't feel super strongly about it either way.

**Comment by llllllllll** [comment]
+1 also, I think the runtime error is fine because I don't expect anyone to want to catch this

**Comment by richafrank** [comment]
Ok, cool, then I'm going to merge on travis passing.

**Pull request merged**
