### PR TITLE
Added load_from_google method

### PR DESCRIPTION
**Pull request by MarkDunne**
Adds the option to load finance data from google instead of yahoo

### CODE REVIEW

**Comment by llllllllll** [comment]
@MarkDunne Is this still something that you are planning on working on?

**Comment by femtotrader** [comment]
I wrote some month ago Pandas unofficial DataReaders (with requests-cache to cache queries)
http://pandas-datareaders.readthedocs.org/

There is a DataReader for Google Finance Daily and Google Finance Intraday
https://github.com/femtotrader/pandas_datareaders/blob/master/tests/test_datareader_google_finance_intraday.py
and
https://github.com/femtotrader/pandas_datareaders/blob/master/tests/test_datareader_google_finance_daily.py

Maybe it could help

**Comment by twiecki** [comment]
@femtotrader This is great! I wonder if we should just refer to your library here and add a few examples of how to fetch different data (including minutely) and run zipline backtests.

**Comment by femtotrader** [comment]
Hello,

First

    $ pip install pandas_datareader

or get latest source version 

    $ git clone https://github.com/femtotrader/pandas_datareaders
    $ cd pandas_datareader

You can do

    from pandas_datareaders import DataReader

    expire_after = 60*60 # cache query in second (see requests-cache doc)
    symbol = "..."
    df = DataReader("GoogleFinanceIntra", expire_after=expire_after).get(symbol, start, end)

`df` is a Pandas DataFrame with minutes Google Finance OHLCV data

see `tests` directory
for example : 
https://github.com/femtotrader/pandas_datareaders/blob/master/tests/test_datareader_google_finance_intraday.py

I'm aware that doc need to be improved.

if symbol is a list of symbol DataReader get method will returns a Pandas Panel

feel free to fork and improve it.

Kind regards

Femto

**Comment by femtotrader** [comment]
Hello,

you might also be interested by 
https://github.com/femtotrader/ig-markets-rest-api-python-library

you can fetch OHLCV historical data (ask, bid and last) from IG Market using `fetch_historical_prices_by_epic_and_num_points` or `fetch_historical_prices_by_epic_and_date_range`
It returns a DataFrame with hierarchical columns (ask, bid and last for level 0 and Open High Low Close Volume for level 1)

Doc also needs to be improved but test file can help to understand how it works
https://github.com/femtotrader/ig-markets-rest-api-python-library/blob/master/tests/test_ig_service.py

I should also improve this code to be able to pass a `session` parameter because there is no cache in this version.

Download data by chunk is probably also an other improvement to make.

`fetch_historical_prices_by_epic_and_num_points` or `fetch_historical_prices_by_epic_and_date_range` should also supports `epic`(symbol) as a list (instead of string) and it should returns a Panel of OHLCV historical data

Kind regards

**Comment by twiecki** [comment]
What's also interesting is that your code uses request cache while we are implementing our own caching mechanism which might then become obsolete (let me know if that's true or not).

So one idea would be make certain `pandas_datareaders` functions available through `zipline.utils.data` and add it as an optional dependency. Is it up on pypi?

**Comment by femtotrader** [comment]
it's also using `requests` package.
For now there is no cache mechanism in `ig_service` (`ig-markets-rest-api-python-library`)
but as I'm using `requests`, it's quite easy to add this using `requests-cache`
I'm quite busy now but I will do it friday or next week.
I'm just add it
https://github.com/femtotrader/ig-markets-rest-api-python-library/issues/2
as a reminder

About `pandas_datareaders` that's a pleasure to see that you want to add it as an optional dependency to `zipline`
it "should" be latest version on pypi

**Comment by twiecki** [comment]
Looks like there's good progress in delineating this with `pandas`. Personally, I'd love to defer responsibility of data loaders to your project which also handles caching and make this a required dependency.

**Comment by femtotrader** [comment]
Thanks Thomas

**Comment by femtotrader** [comment]
Cache mechanism for ig-market REST API works now
see https://github.com/femtotrader/ig-markets-rest-api-python-library

you can cache globally passing session to IGService

    service = IGService(config.username, config.password, config.api_key, config.acc_type, session)
    ig_service.create_session()

or only for a specific method

like

    epic = 'CS.D.EURUSD.MINI.IP'
    resolution = 'D'
    start_date = '2014-12-15'
    end_date = '2014-12-20'
    response = ig_service.fetch_historical_prices_by_epic_and_date_range(epic, resolution, start_date, end_date, session)

Travis CI works fine for Python 2.7, 3.3 and 3.4

same for
https://github.com/femtotrader/pandas_datareaders_unofficial/
but I hope to have cache in official Pandas DataReader which is now a separate package
https://github.com/pydata/pandas-datareader

pip packages are updated

**Comment by FreddieV4** [comment]
Hi @MarkDunne I'm going to go ahead and close this PR as it's been a while since any updates. We're removing `load_bars_from_yahoo()` and so a similar method `load_bars_from_google` would need to be a bundle instead. 

Feel free to open comment here if you'd like to still add this sort of functionality.

**Pull request closed without merging**
