### PR TITLE
ENH: upgrade pandas to 0.19.2

### PR DESCRIPTION
**Pull request by kennell**
Hi folks. This upgrades Pandas to version 0.19.2 and fixes some issues dealing with the pickle'd output when using Python 3.6, see https://github.com/pandas-dev/pandas/issues/14679 for details on the issue.

### CODE REVIEW

**Comment by Peque** [comment]
Maybe project admins can re-run the Travis build, which seems it never reported back. Otherwise maybe you could try to push some changes to force update?.

I would use `'pandas': '<0.20'` in `REQ_UPPER_BOUNDS` instead (just like there was `<0.19` before). That way future minor `0.19.x` versions can be used as well (minor are usually just bug fixes and do not break things).

**Comment by kennell** [comment]
Folks, any chance we can get this merged? Regarding the travis test, perhaps someone can re-trigger.

**Comment by richafrank** [comment]
Hey @kennell , could you tell us more about what this fixes?

I see two changes here: 

1. The first increments the lower bound of required pandas versions, which I don't think we want to do. The quantopian platform on the website is running zipline with the lower pandas version, so we very much want to support that version right now.
1. The second increments the upper bound of support, which I don't have a strong opinion on, assuming zipline works. It looks like travis and appveyor are running tests only with the lower bound version, so could you update the test matrix to assess both the lower and upper? I believe @ssanderson last bumped that upper bound, so probably he could share how he chose the version listed on master.

Thanks!

**Comment by richafrank** [comment]
> Folks, any chance we can get this merged? Regarding the travis test, perhaps someone can re-trigger.

Travis doesn't seem to know about that build, so there's nothing I can re-run. Want to update your branch to trigger a new run?

**Comment by Peque** [comment]
Note that you may need to update some other files (see #1810).

Also, I would rather set `'pandas': '<0.20'` for the upper bounds, to allow future minor versions, which could fix bugs but should not break compatibility.

**Comment by FreddieV4** [comment]
Going to close this due to inactivity. Feel free to re-open or open a new PR 🙂

**Comment by Peque** [comment]
Created #1975 for those who wish to subscribe/comment.

**Pull request closed without merging**
