### PR TITLE
BUG: Replaced deprecated operators for pd.Index

### PR DESCRIPTION
**Pull request by lianga888**
Replaced + and - with union and difference, respectively

### CODE REVIEW

**Comment by ssanderson** [comment]
@lianga888 do we have a repro case for the algos that this was breaking?  If so can we add a test to verify that this in fact fixes the crash?

**Comment by llllllllll** [comment]
https://www.quantopian.com/posts/function-that-is-not-called-crashes-backtest-returns-will-not-work-either

I think this hits the case

**Comment by lianga888** [comment]
Okay, I can write a test for it

**Comment by lianga888** [comment]
This was the corresponding zipline PR for https://github.com/quantopian/qexec/pull/5999, which is now closed

**Pull request closed without merging**
