### PR TITLE
ENH: Add CLOSE_POSTION as DataSource event type

### PR DESCRIPTION
**Pull request by warren-oneill**
This PR enables signals to be sent from ```DataSource``` which tells zipline to close any open positions for the given sid.

Note: this PR uses code from #592 and borrowed lines from the __futures-trading__ branch.
cc @ehebert @jfkirk

### CODE REVIEW

**Comment by jfkirk** [comment]
Looks good - running tests now.

**Comment by jfkirk** [comment]
Tests look good. Merged. Thanks, Warren!

**Comment by warren-oneill** [comment]
@jfkirk thanks man! This'll make my life a lot easier!

**Comment by warren-oneill** [comment]
@jfkirk could you add the changes to __futures-trading__?

**Pull request merged**
