### PR TITLE
Fix error like data[symbol('AAPL')]

### PR DESCRIPTION
**Pull request by waveyeung**
also fix data[sid(0)]

### CODE REVIEW

**Comment by richafrank** [comment]
Hi @waveyeung ,  Thanks for the PR.  Do you have an example of code that was failing without this change?  

Also, have you tried using the latest of zipline master from github?  I ask because this was likely already fixed by #959.  On latest master, I see:
```python
In [1]: from zipline.assets import Equity

In [2]: d = {1: 'found'}

In [3]: d[Equity(sid=1)]
Out[3]: 'found'
```
even with 32-bit python, so the explicit use of the `sid` attribute should be unnecessary.

**Comment by waveyeung** [comment]
Hi @richafrank 
My env is zipline-0.8.3 from pip, py2.7

```
from zipline.api import record, symbol, symbols, sid

def initialize(context):
    context.stocks = symbols('AAPL', 'MFST')

def handle_data(context, data):
    for stock in encontext.stocks:
        price = data[stock].price # or price = data[sid(0)].price
```

code raise excetption:

>   File "C:\Python27\lib\site-packages\zipline\protocol.py", line 521, in __getitem__
>     return self._data[name]
> KeyError: Equity(0, symbol=u'AAPL', asset_name=None, exchange=None, start_date=Timestamp('1970-01-01 00:00:00+0000', tz='UTC'), end_date=Timestamp('2116-02-20 23:53:38.427387903+0000', tz='UTC'), first_traded=None

checked source code at zipline master from github, it doesn't seems to solve the problem.

**Comment by waveyeung** [comment]
Hi @richafrank 
I found master fix the problem, good job!

**Comment by richafrank** [comment]
Great - glad to hear it!

**Pull request closed without merging**
