### PR TITLE
Refactor Security to Asset

### PR DESCRIPTION
**Pull request by jfkirk**
This commit refactors the Security cython class to Asset, and refactors some fields of the class accordingly. This change is so the terminology is consistent and correct when Asset is extended to asset types that are not securities, such as futures.

### CODE REVIEW

**Comment by llllllllll** [comment]
:+1: on clear naming

**Comment by ehebert** [comment]
The tests pass locally for me as well, I just kicked off a new Travis build to see if the error is repeatable.

**Comment by ehebert** [comment]
Besides the tests, this looks good to me.

Perhaps also add Security to the module as a subclass to show how it would be used as a base?

**Comment by jfkirk** [comment]
@ehebert Will do. This PR should not be merged until that has been added.

**Comment by jfkirk** [comment]
@ehebert Added extensions for Equity and Future, as we've discussed. I also added a test for the Future class that checks that the fields are assigned properly and reported through the repr. Thanks so much for all of your help.

**Pull request merged**
