### PR TITLE
add true range technical factor

### PR DESCRIPTION
**Pull request by ChrisPappalardo**

### CODE REVIEW

**Comment by ChrisPappalardo** [comment]
@llllllllll I wrote that section we discussed using pure python to better understand your rolling_window suggestion and it seems to me that the slices in [_calc_true_range(highs[i:i+1], lows[i:i+1], closes[i:i+1]) for i in range(0, self.params['i'])] look a lot like what rolling_window does... I'll keep working on it and add it to the PR.

**Comment by llllllllll** [comment]
@ChrisPappalardo do you think you will have time to finish working on this soon, if not we can finish this up for you.

**Comment by ChrisPappalardo** [comment]
Sorry Joe, I was pulled off this by work stuff.  I can spend some time on this tomorrow and see if I can wrap it up.

**Comment by llllllllll** [comment]
No rush, I just wanted to check in. lmk if you need any help.

**Comment by llllllllll** [comment]
merged in #1348, Thanks!

**Comment by ChrisPappalardo** [comment]
Thanks Joe.  I've been slammed at work ever since Pycon.  I'll get back to the other parts of this PR once things slow down.  Hope all is well with you.

**Pull request closed without merging**
