### PR TITLE
ENH: Removes dependence of BcolzMinuteBarReader on 390 minutes per day

### PR DESCRIPTION
**Pull request by yankees714**
Adds a `minutes_per_day` field to `BcolzMinuteBarMetadata`, so that the `minutes_per_day` value passed to the `BcolzMinuteBarWriter` is written as a part of the minute bar metadata. This allows the reader to share this value, instead of always assuming 390.

Also rebuilds the example data to incorporate this format change.

### CODE REVIEW

**Comment by richafrank** [comment]
If I'm a user of (standalone) zipline, and I've previously downloaded a bunch of pricing data to bcolz files, will upgrading the version of zipline mean I can't read those pricing files anymore?

**Comment by ehebert** [comment]
@richafrank, it would. What do you think about adding a fallback value of `390` with a deprecation warning saying something akin to `No minutes_per_day found, defaulting to 390.`

**Comment by richafrank** [comment]
@ehebert That makes sense.  If we have a way to add the metadata to the files in place, then the warning could also tell users to do that.

**Comment by ehebert** [comment]
Also, this seems like a case where we should have a file format upgrade path?

**Comment by richafrank** [comment]
Yup, exactly.

**Comment by ehebert** [comment]
@richafrank how do you feel about not building a full upgrade system for the file format for the benefit of this PR, but setting version `1` for incoming format, and then adding a check that looks for the `version` field in the metadata and if it is not found version `0` is found.

Then if version `1` is present look for `minute_per_day` else default to 390 (Equities).

**Comment by richafrank** [comment]
@ehebert Sounds good to me.  We can build more later.

**Comment by ehebert** [comment]
@richafrank https://github.com/quantopian/zipline/pull/1341/commits/d0704fe3f569555b3de108818b739b09cc76d735 is a simple implementation of the fallback to version 0 and providing a default for minutes per day. Mind taking a look?

**Comment by richafrank** [comment]
Makes sense to me!  Thanks @ehebert

**Comment by ehebert** [comment]
@yankees714 the updated example data had an encoding issue with Python 3. With the addition of having a fallback value for the data, the existing data is usable, so I edited your patch to remove change to the sample data.

**Pull request merged**
