### PR TITLE
Run panel of assets

### PR DESCRIPTION
**Pull request by richafrank**
Running an algo with a df/panel of Assets was raising SidNotFound

```retrieve_asset``` returns its argument if it's an Asset.  In ```run```, we want to ensure that Asset is in the db first, so pass the asset's sid attribute to ```retrieve_asset``` to get a real answer about whether it's already in the db.

### CODE REVIEW

**Comment by richafrank** [comment]
cc @jfkirk

**Comment by adzuci** [comment]
Yay =).

**Comment by KarenRubin** [comment]
@richafrank do you need help testing this?

**Comment by richafrank** [comment]
@KarenRubin I should be good.

**Comment by jfkirk** [comment]
This is a lot cleaner than what I had -- thanks, Rich!

**Pull request merged**
