### PR TITLE
TST: Fixes test_order_methods_for_future

### PR DESCRIPTION
**Pull request by jfkirk**
Fixes test_order_methods_for_future by creating a separate env where 0 is a Future.

### CODE REVIEW

**Comment by jfkirk** [comment]
@llllllllll Mind giving this a peek?

**Comment by jfkirk** [comment]
Ping @llllllllll

**Comment by llllllllll** [comment]
Why was this passing before?

**Comment by jfkirk** [comment]
The test algo itself checks the type of the Asset it is ordering. Because the wrong Asset was coming back from the env, the test algo was following its Equity logic in stead of its Future logic.

An alternate solution would be to dupe the test algos, one for Equities, and one for Futures, but that would be a lot more verbose.

**Comment by llllllllll** [comment]
I would probably prefer that we make the tests more verbose because this is passing on both master and this branch. The test should not work with equities

**Comment by jfkirk** [comment]
How about I add an assertion to both the equity and future tests that ensures that the desired sid is the desired asset type? Then, if something happens to the environments that changes the asset type, it would be caught by the test itself.

**Comment by llllllllll** [comment]
That sounds good.

**Comment by jfkirk** [comment]
I added assertions to both tests and verified that these assertions would have failed without the new env.

**Comment by llllllllll** [comment]
looks good, merge on pass

**Pull request merged**
