### PR TITLE
MAINT: add buyback auth to factors init.

### PR DESCRIPTION
**Pull request by mtydykov**
Forgot to add buyback auth factors to `__init__`. Also, small formatting fixes.

### CODE REVIEW

**Comment by llllllllll** [comment]
lgtm, @richafrank any idea about the gfortan stuff?

**Comment by mtydykov** [comment]
There's also an import error? Doesn't seem related to any of my changes.

**Comment by richafrank** [comment]
> lgtm, @richafrank any idea about the gfortan stuff?

I think we need to pin the version of libgfortran that we're conda installing to whatever last passed (I think 1 instead of 3?).

**Comment by mtydykov** [comment]
Is that something I should do in this PR? Or elsewhere?

**Comment by richafrank** [comment]
Seems to be failing for other PRs too, so could fix it separately.

**Comment by richafrank** [comment]
Should be fixed on maser now.

**Pull request merged**
