### PR TITLE
Perform account validation at the end of the day

### PR DESCRIPTION
**Pull request by dmichalowicz**

### CODE REVIEW

**Comment by dmichalowicz** [comment]
@richafrank Updated. I removed the test I added because this behavior is already being tested here: https://github.com/quantopian/zipline/blob/master/tests/test_algorithm.py#L3511

**Comment by richafrank** [comment]
> I removed the test I added because this behavior is already being tested

Nice - does that mean the existing test didn't care about minutely versus daily?

**Comment by dmichalowicz** [comment]
> does that mean the existing test didn't care about minutely versus daily?

Correct, it's simply checking that the appropriate exception is raised when running an algo under the leverage constraint. Do you think this is sufficient?

**Comment by richafrank** [comment]
I suppose we could test to see how far the backtest got. I don't have a strong opinion in this case.

**Comment by dmichalowicz** [comment]
@richafrank I added a time check to the test.

**Comment by dmichalowicz** [comment]
@richafrank Good to go?

**Comment by richafrank** [comment]
:shipit:

**Pull request merged**
