### PR TITLE
MAINT: allows contract_multiplier to be non-integer

### PR DESCRIPTION
**Pull request by warren-oneill**
is float the right choice here?
cc @jfkirk

### CODE REVIEW

**Comment by jfkirk** [comment]
@ehebert Any reason we shouldn't use a float to represent non-integer contract_multipliers on Futures?

If not, this PR is good-to-go.

**Comment by ehebert** [comment]
`float` looks correct to me.

**Comment by jfkirk** [comment]
@StewartDouglas I believe this PR is ready to merge - can you give it a once-over and pull the trigger?

**Comment by StewartDouglas** [comment]
LGTM, thanks @warren-oneill. Merging.

**Comment by StewartDouglas** [comment]
Cherry-picked onto master. Closing.

**Comment by warren-oneill** [comment]
@StewartDouglas np :smile:

**Pull request closed without merging**
