### PR TITLE
WIP: General perf enhancements

### PR DESCRIPTION
**Pull request by dalejung**
This is mainly targeted at minutely backtests with daily emissions. Having a 1-to-1 emission causes the perf tracking to dominate performance, which I haven't touched. 

Can someone else run this and let me know the timings? Especially with an algo that's public and that I can also run.

### CODE REVIEW

**Comment by twiecki** [comment]
Wow, just ran a poor-man's profiling of this by running `tests/test_history.py` with the nose-timer plugin.

With pandas 0.15.2 on master:
```
tests.test_history.TestHistoryAlgo.test_history_grow_length_intra_bar_0: 9.8875s
tests.test_history.TestHistoryAlgo.test_history_grow_length_intra_bar_1: 9.4591s
tests.test_history.TestHistoryAlgo.test_history_grow_length_inter_bar_0: 6.7784s
tests.test_history.TestHistoryAlgo.test_history_grow_length_inter_bar_1: 6.3989s
tests.test_history.TestHistoryContainer.test_history_container_4_test_mixed_frequencies: 5.9189s
tests.test_history.TestHistoryAlgo.test_history_container_constructed_at_runtime_1_minute: 5.6720s
tests.test_history.TestHistoryAlgo.test_history_passed_to_talib: 5.2621s
tests.test_history.TestHistoryAlgo.test_basic_history: 3.7849s
tests.test_history.TestHistoryAlgo.test_basic_history_positional_args: 3.3764s
tests.test_history.TestHistoryAlgo.test_basic_history_one_day: 2.9006s
----------------------------------------------------------------------
Ran 337 tests in 71.159s
```
With pandas 0.15.2 on this branch:
```
tests.test_history.TestHistoryAlgo.test_history_grow_length_intra_bar_0: 2.6139s
tests.test_history.TestHistoryAlgo.test_history_grow_length_intra_bar_1: 2.4586s
tests.test_history.TestHistoryAlgo.test_history_grow_length_inter_bar_1: 1.8264s
tests.test_history.TestHistoryAlgo.test_history_grow_length_inter_bar_0: 1.7328s
tests.test_history.TestHistoryAlgo.test_history_container_constructed_at_runtime_1_minute: 1.4697s
tests.test_history.TestHistoryContainer.test_history_container_4_test_mixed_frequencies: 1.4078s
tests.test_history.TestHistoryAlgo.test_history_passed_to_talib: 1.0934s
tests.test_history.TestHistoryAlgo.test_basic_history: 1.0417s
tests.test_history.TestHistoryAlgo.test_basic_history_one_day: 0.9016s
tests.test_history.TestHistoryAlgo.test_basic_history_positional_args: 0.7574s
----------------------------------------------------------------------
Ran 337 tests in 19.058s
```

That's a 3.7x speed improvement! Any reason why we shouldn't just merge this? Seems like initial code review didn't reveal anything major and it passes all tests.

**Comment by twiecki** [comment]
For reference, this is master with pandas 0.12:
```
tests.test_history.TestHistoryAlgo.test_history_grow_length_intra_bar_0: 6.0197s
tests.test_history.TestHistoryAlgo.test_history_grow_length_intra_bar_1: 5.6182s
tests.test_history.TestHistoryAlgo.test_history_grow_length_inter_bar_0: 3.9811s
tests.test_history.TestHistoryAlgo.test_history_grow_length_inter_bar_1: 3.9406s
tests.test_history.TestHistoryAlgo.test_history_container_constructed_at_runtime_1_minute: 3.4218s
tests.test_history.TestHistoryContainer.test_history_container_4_test_mixed_frequencies: 3.2790s
tests.test_history.TestHistoryAlgo.test_history_passed_to_talib: 2.8080s
tests.test_history.TestHistoryAlgo.test_basic_history: 2.4622s
tests.test_history.TestHistoryAlgo.test_basic_history_positional_args: 2.1499s
tests.test_history.TestHistoryAlgo.test_basic_history_one_day: 1.6705s
----------------------------------------------------------------------
Ran 337 tests in 42.205s
```

Significantly slower than with pandas 0.15.2 on master (but slower than this PR).

**Comment by ssanderson** [comment]
@twiecki it's also not functional on older pandas, which we still ostensibly support.

**Comment by twiecki** [comment]
Right, but as we're upgrading to 0.15 anyhow this could be tucked in.

**Comment by ehebert** [comment]
Makes sense to combine the two branches to me.

**Comment by dalejung** [comment]
What part doesn't run under 0.12? I'll admit, I'm guilty of even writing python 3 specific code these days :/. I assumed travis was testing 0.12.0 but it looks to be 0.15.2?

**Comment by ssanderson** [comment]
@dalejung `pandas.core.common.interpolate2d` (used here: https://github.com/quantopian/zipline/pull/458/files#diff-803238601658da56278f98e2fa62ae88R46) doesn't exist in 0.12.

**Comment by twiecki** [comment]
@dalejung travis has for a long time used pandas 0.15.2.

**Comment by dalejung** [comment]
@twiecki Can 0.12.0 be added back in? Maybe not a complete matrix but making the python 2 test run with 0.12.0. 

@ssanderson ah yeah. That's easy enough, the 0.15 stuff just added another layer of indirection.

**Comment by twiecki** [comment]
@dalejung Can't find `interpolate_2d` in pandas 0.12. Where is that supposed to reside?

**Comment by dalejung** [comment]
It doesn't exist. The older Block stuff called the interpolate sub methods directly.

**Comment by dalejung** [comment]
newer stuff just passes along the method param to `interpolate_2d` which handles the offloading

**Comment by twiecki** [comment]
Closing at it's superseded by https://github.com/quantopian/zipline/pull/488 and https://github.com/quantopian/zipline/pull/486.

**Pull request closed without merging**
