### PR TITLE
have pandas/numpy match for requirements.txt in travis

### PR DESCRIPTION
**Pull request by dalejung**
I just ran into a 1.8.0<>1.8.1 compat difference.

### CODE REVIEW

**Comment by dalejung** [comment]
I just https://github.com/quantopian/zipline/pull/353 and added an all latest versions test case. Tempted to have pandas checkout from master but that's probably more for https://github.com/quantopian/zipline/issues/500

**Comment by dalejung** [comment]
@twiecki @richafrank what's the process to get a py3.4 build up on the Quantopian binstar?

**Comment by richafrank** [comment]
I've been following https://github.com/quantopian/zipline/tree/master/conda#conda-build-files and/or asking @twiecki each time.

**Comment by twiecki** [comment]
There's also:
https://quantopian.atlassian.net/wiki/display/ENG/Create+conda+zipline+packages

On Thu, Feb 26, 2015 at 4:44 PM, Richard Frank <notifications@github.com>
wrote:

> I've been following
> https://github.com/quantopian/zipline/tree/master/conda#conda-build-files
> and/or asking @twiecki <https://github.com/twiecki> each time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/quantopian/zipline/pull/511#issuecomment-76200679>.
>



-- 
Thomas Wiecki, PhD
Data Science Lead, Quantopian Inc, Boston

**Comment by richafrank** [comment]
Closing, since this looks pretty out of date now.

**Pull request closed without merging**
