### PR TITLE
Blotter perf

### PR DESCRIPTION
**Pull request by dalejung**
This puts an upper bound on the perf regression from having many orders open for the same sid.

### CODE REVIEW

**Comment by ehebert** [comment]
This looks good to me. Maybe just update the Allow SlippageModels liquidity commit with more details about how it gets into that factorial problem you mentioned and then it would be good to go.

**Comment by dalejung** [comment]
@eddie @twiecki can you click and rebuild this in travis. I don't have the access.

**Comment by twiecki** [comment]
Done.

**Comment by ehebert** [comment]
Merged via 94d25a54c607d0379aa25f80cbbb79617467d583

**Pull request closed without merging**
