### PR TITLE
BUG: missing comma in _asset_timestamp_fields

### PR DESCRIPTION
**Pull request by warren-oneill**
surprised this wasn't caught by any of the tests. Should we add an extra one?

### CODE REVIEW

**Comment by ssanderson** [comment]
Oof.  Thanks for the catch.  We're currently doing:

```
def _convert_asset_timestamp_fields(dict):
    """
    Takes in a dict of Asset init args and converts dates to pd.Timestamps
    """
    for key, value in dict.items():
        if (key in _asset_timestamp_fields) and (value is not None):
            dict[key] = pd.Timestamp(value, tz='UTC')
```
when we pull an entry out of the database.  Both for efficiency and correctness, this loop should probably be:

```
def _convert_asset_timestamp_fields(dict):
    """
    Takes in a dict of Asset init args and converts dates to pd.Timestamps
    """
    for key in _asset_timestamp_fields:
        value = dict[key]

        if (key in _asset_timestamp_fields) and (value is not None):
            dict[key] = pd.Timestamp(value, tz='UTC')
```

**Comment by ssanderson** [comment]
@jfkirk @StewartDouglas `_convert_asset_str_fields` is also almost certainly broken.

```
def _convert_asset_str_fields(dict):
    """
    Takes in a dict of Asset init args and converts from unicode to string
    where applicable
    """
    for key, value in dict.items():
        if key in _asset_str_fields:
            dict[key] = str(value)
```

This will return `bytes` in Python 2 and `unicode` in Python 3.  The statement "converts from unicode to string" is not meaningful in a Python 2/3 compat library.

**Comment by jfkirk** [comment]
Good catches all around - apologies for not factoring in 2/3 compatibility when writing that.

This PR looks good - I'm merging it then opening an issue to tackle Scott's catches.

**Comment by jfkirk** [comment]
Issue open for other fixes:
https://github.com/quantopian/zipline/issues/740

Merging this PR now.

**Pull request merged**
