### PR TITLE
Updated Requirements 

### PR DESCRIPTION
**Pull request by warren-oneill**
I have been trying to implement the zipline development environment and I ran into a lot of problems with the packet versions in requirements.txt. The problems were either compilation errors or failing unittests.
The settings which worked for me are:
* pandas==0.14.1
* statsmodels==0.6.1

and everything else as it is in the master branch.

Note: I changed pip to pip3 for the installation but it should also work for pip.

### CODE REVIEW

**Comment by twiecki** [comment]
Newer versions of pandas did not work?

**Comment by warren-oneill** [comment]
They did but then it conflicted with the dateutil version and it was unable to read the data from yahoo. I tried to implement it with few changes as possible.

**Comment by twiecki** [comment]
Thanks, but closing in favor of #526.

**Comment by warren-oneill** [comment]
Newer is better :) Fingers crossed those versions work on my machine

**Pull request closed without merging**
