### PR TITLE
Fix sharpe ratio

### PR DESCRIPTION
**Pull request by twiecki**
Supersedes #874

See #853.

### CODE REVIEW

**Comment by FayolChang** [comment]
@twiecki , doc of sharpe_ratio in risk.py says the second parameter---treasury_return,  is Annual treasury return percentage. but calculate_sharp in cumulative.py pass a daily_treasury to sharp_ratio.

also, note that param algorithm_return in calculate_sharp is an array, it does not have an index.

I assume that you want to calculate annualized sharpe ratio from daily algorithm return. In this case, calculate_sharpe should not be called daily(i.e. should not update every trading day)

F.Y.I.

https://www.quantstart.com/articles/Sharpe-Ratio-for-Algorithmic-Trading-Performance-Measurement

**Comment by twiecki** [comment]
Thanks @FayolChang.

>@twiecki , doc of sharpe_ratio in risk.py says the second parameter---treasury_return, is Annual treasury return percentage. but calculate_sharp in cumulative.py pass a daily_treasury to sharp_ratio.

I believe `daily_treasury` refers to the annual risk-free rate on every day. At least, I don't see where any decompounding is being done. 

> also, note that param algorithm_return in calculate_sharp is an array, it does not have an index.

You're right, that needs to be fixed yet.

> I assume that you want to calculate annualized sharpe ratio from daily algorithm return. In this case, calculate_sharpe should not be called daily(i.e. should not update every trading day)

That's correct and something we wanted to fix for some time but it's a larger refactoring and I'd rather fix it here and make it more efficient later.

**Comment by llllllllll** [comment]
Could you add a whatsnew entry?

**Comment by dunster** [comment]
I'd like to talk to Joe and Rich about this before we merge - will track everyone down tomorrow morning.

**Comment by twiecki** [comment]
Currently pondering this change which breaks this PR: https://github.com/quantopian/zipline/commit/bfa94e9c91fae2316f587fb6c84a124dc93411c5 by @ehebert. It causes algo returns to have a different length than the other metrics. I think a better approach would be to just set risk metrics to nan if they can't be computed if e.g. only a single day is present.

**Comment by ehebert** [comment]
@twiecki I think a `nan` on the first day makes sense. For some context, that patch was to provide compatibility with live trading (minute emission) results on the first day.

**Comment by dunster** [comment]
We talked yesterday. Thomas is the master of deciding "what is right" and is also the person who should reach out and let us know when changes are coming.

**Comment by twiecki** [comment]
I think this fix is pretty critical but it's turning into a bigger challenge to make changes to the risk metrics than anticipated.

**Comment by twiecki** [comment]
I could use some engineering help to get this over the finish line. Specifically, the pattern of appending zeros (https://github.com/quantopian/zipline/commit/bfa94e9c91fae2316f587fb6c84a124dc93411c5) should be reverted and instead support nans.

**Comment by twiecki** [comment]
Unfortunately I still don't have time to fix the nan issue properly. The math in this PR is correct but it'd be great if someone could help solving that last issue and fixing up the tests.

**Comment by dunster** [comment]
#8343

**Comment by twiecki** [comment]
Closing in favor of https://github.com/quantopian/zipline/pull/1322.

**Pull request closed without merging**
