### PR TITLE
ENH: Adding CFE Adhoc Holidays

### PR DESCRIPTION
**Pull request by trical09**
@FreddieV4 Fixed, redone #1682 

CBOE and CFE observed the USNationalDaysofMourning and HurricaneSandyClosings:

USNationalDaysofMourning
http://www.mondovisione.com/news/cboe-and-cfe-will-be-closed-on-tuesday-january-2-to-honor-former-president-geral/
https://www.cboe.com/aboutcboe/legal/bulletins/archives/documents/eb062504.pdf

HurricaneSandyClosings
http://ir.cboe.com/press-releases/2012/29-oct-2012.aspx
http://www.cboe.com/publish/RegCir/RG12-146.pdf

exchange_calendar_cfe.CFEExchangeCalendar

should have the following:

```
@property
 def adhoc_holidays(self):
     return list(chain(
         HurricaneSandyClosings,
         USNationalDaysofMourning,
     ))
```

### CODE REVIEW

**Comment by trical09** [comment]
Now I need to fix the unit test for CFECalendar

**Comment by trical09** [comment]
@FreddieV4 now fixed

**Comment by FreddieV4** [comment]
Hey @trical09 this looks good to me. If you just squash your commits, and change your commit prefix to be consistent with our [dev guidelines](https://github.com/quantopian/zipline/wiki/Zipline-development-guidelines) then I think this should be good to merge (I think `ENH` is appropriate for this PR)

**Comment by FreddieV4** [comment]
I think if you rebase against zipline master, and the force push to this branch, you might fix the problem of adding 34 new commits rather than just the ones you added 😃

**Comment by trical09** [comment]
Apologies on this being such a disaster. I think it should work now.

**Comment by FreddieV4** [comment]
No problem. It happens every now and then. Thanks for your contribution!

**Pull request merged**
