### PR TITLE
BUG: orders future chain by min of notice and expiry

### PR DESCRIPTION
**Pull request by warren-oneill**
Is the chain intentionality ordered by expiry? For me ordering by the min makes more sense.

### CODE REVIEW

**Comment by ssanderson** [comment]
@warren-oneill this makes sense to me, but I want to confirm with @jfkirk.  Assuming this is desired behavior, can we slot in a test somewhere in `test_assets` that exercises this behavior?

**Comment by jfkirk** [comment]
Are there situations where ordering by the min would produce a different order than ordering by the expiry? It definitely makes sense to order by the min to me, but I wonder if adding the comparison would be an extra comparison for no impact.

**Comment by warren-oneill** [comment]
@jfkirk  For me yes but it depends if the difference between notice and expiry in your cases is constant of if it can vary between assets.

**Comment by jfkirk** [comment]
OK, then this makes sense to me, but ditto what @ssanderson about a test
@yankees714 does this make sense to you?

**Comment by yankees714** [comment]
Yep, make sense.

@warren-oneill could we update the comment above the `sa.case` statement? It's no longer correct given this change.

**Comment by warren-oneill** [comment]
@jfkirk @ssanderson @yankees714 corrected the comment and adjusted the test so it examines the notification date. Is the test adjustment enough or do I need more?

**Comment by yankees714** [comment]
@warren-oneill all makes sense to me now.

**Comment by jfkirk** [comment]
LGTM - will merge today, if nobody objects

**Pull request merged**
