### PR TITLE
adding net leverage, long/short exposure, long/short position count

### PR DESCRIPTION
**Pull request by fawce**
to performance packets.

### CODE REVIEW

**Comment by twiecki** [comment]
`zipline/finance/performance/period.py:349:80: E501 line too long (80 > 79 characters)`

**Comment by twiecki** [comment]
We should also add the new leverage features to the release docs.

**Comment by twiecki** [comment]
:+1:

**Comment by fawce** [comment]
@twiecki I updated the release notes. let me know if I did it right :).

**Comment by fawce** [comment]
passed performance review with @ehebert so merge time

**Pull request merged**
