### PR TITLE
MAINT: Upgrade to newer version of `werkzeug`

### PR DESCRIPTION
**Pull request by cmichelQT**
@richafrank Okay to merge?

### CODE REVIEW

**Comment by cmichelQT** [comment]
Appveyor failed, investigating.

**Comment by jikquantopian** [comment]
See https://github.com/quantopian/zipline/pull/2353. There is a problem with `requests`.

**Comment by jikquantopian** [comment]
Ignore my last comment, I was confused.

**Comment by richafrank** [comment]
FYI All our AppVeyor builds for the "Old pandas/numpy" stack are currently suffering from https://github.com/ContinuumIO/anaconda-issues/issues/10378.

**Comment by richafrank** [comment]
Build is fixed now. Change makes sense to me, assuming no new transitive dependencies need pinning.

**Comment by cmichelQT** [comment]
@richafrank Confirmed with this change there are no transitive dependencies that need to be pinned.

**Pull request merged**
