### PR TITLE
Python 3.6 Support

### PR DESCRIPTION
**Pull request by dmichalowicz**
Attempting https://github.com/quantopian/zipline/pull/2512#issuecomment-576903728 by opening a branch as a Quantopian member. All credit for these changes goes to @Peque.

### CODE REVIEW

**Comment by Peque** [comment]
Mind commenting here with the results?

https://github.com/quantopian/zipline/issues/2619

Specifying if you:

- Are part of the Quantopian GitHub organization
- Have an AppVeyor paying subscription.
- Made any changes with respect to the original PR (https://github.com/quantopian/zipline/pull/2512)

**Comment by Peque** [comment]
It seems pipelines do not get stuck for you! :blush: 

No idea about [the error](https://ci.appveyor.com/project/Quantopian/zipline/builds/30566064/job/lvyspatppg506id8) though.

**Comment by dmichalowicz** [comment]
I did not make any changes from the [original PR](https://github.com/quantopian/zipline/pull/2512). It looks like maybe we need to bump the version of `psutil`? I'm not on a Windows machine but will try to debug further.

**Comment by Peque** [comment]
@dmichalowicz Yeah, I just tried to bump it in:

https://github.com/quantopian/zipline/pull/2512/commits/514d8c57b8d9eb2db1fc22228b2ab469611de4d0

Let us see if pipelines pass (at least in Travis, you may need to pull the changes into your fork to make AppVeyor pass). :sweat_smile:

**Comment by Peque** [comment]
@dmichalowicz It seems the `psutil` bump worked just fine, so you may want to try and push that last commit from my branch to see if it fixes the AppVeyor remaining issues. :blush:

**Comment by Peque** [comment]
:tada: :blush:

**Comment by dmichalowicz** [comment]
Thanks for your work on this @Peque and for your patience!

**Comment by nerddan** [comment]
When will the Pypi version of Zipline support Python 3.6?

**Pull request merged**
