### PR TITLE
update the IEX API call

### PR DESCRIPTION
**Pull request by yesme**
This is for the issue #2577

### CODE REVIEW

**Comment by lungothrin** [comment]
@yesme you missed a line, `from os import environ`

**Comment by ZippeyKeys12** [comment]
Why not use Yahoo or something that doesn't require another limited API

**Comment by iamanvesh** [comment]
@yesme @lungothrin @ZippeyKeys12  @richafrank When can we expect this fix to make it to a release?

**Comment by richafrank** [comment]
Hi @yesme, Eight months later 😢 , but I think this is superseded by https://github.com/quantopian/zipline/pull/2642. That's on master now, but it isn't released on PyPI yet.

Feel free to ping in https://github.com/quantopian/zipline/issues/2627 or reopen this if you think this is still useful!

**Pull request closed without merging**
