### PR TITLE
BUG: Prevents payout of dividend on final trading close

### PR DESCRIPTION
**Pull request by jfkirk**
@jdricklefs This is to fix the bug we noticed.

### CODE REVIEW

**Comment by jbredeche** [comment]
can we get a unit test for this?

**Comment by jfkirk** [comment]
Yep - will add.

**Comment by jfkirk** [comment]
@jbredeche Test added.

**Comment by jbredeche** [comment]
thanks cap'n.

**Comment by jdricklefs** [comment]
Cherry-picked to master via 9291a89

Thanks, @jfkirk !

**Pull request closed without merging**
