### PR TITLE
ENH: Add NotNullFilter.

### PR DESCRIPTION
**Pull request by ssanderson**

### CODE REVIEW

**Comment by llllllllll** [comment]
What is wrong with `~self.isnull()`?

**Comment by ssanderson** [comment]
> What is wrong with ~self.isnull()?

Downstream @mtydykov wanted to write a Filter that was `NotNullFilter` with default inputs, and implementing it here and using it for `notnull` saves an intermediate array in the term graph.

**Comment by llllllllll** [comment]
Okay. Do we have the ability to do a graph rewrite rule for `~IsNull` -> `NotNull`?

**Comment by ssanderson** [comment]
> Okay. Do we have the ability to do a graph rewrite rule for ~IsNull -> NotNull?

We're not doing any graph rewriting right now.

**Pull request merged**
