### PR TITLE
Update test matrix to test both pandas 0.12.0 and 0.15.2

### PR DESCRIPTION
**Pull request by dalejung**
So this will test a 2x2 matrix.

py 2.7 pandas 0.12.0
py 2.7 pandas 0.15.2
py 3.3 pandas 0.12.0
py 3.3 pandas 0.15.2

It might be overkill to test all 4. Maybe py 2.7/pandas 0.12.0 and py3.3/pandas 0.15.2 would suffice. 

Either way, if we're supporting 0.12.0 it should be in the test matrix somewhere.

### CODE REVIEW

**Comment by dalejung** [comment]
ooh, need to change the hardcoded numpy 1.9, since it won't work with pandas 0.12.0

**Comment by twiecki** [comment]
We should have done this a long time ago. Hopefully though we're moving away from pandas 0.12 soon though, so I'm not sure how long this will be relevant. If it's easy though I'm all for merging.

**Comment by dalejung** [comment]
The readme says it supports back to pandas 0.9. So we either need to update the minimum deps or run travis on those older versions. 

Travis is failing on pandas 0.12.0 and numpy 1.7.0. Havent' checked if that's just a travis thing, but if it's legit then previous deps are probably already failing too.

**Comment by ehebert** [comment]
I think it would be OK to update README to reflect the version we had been
using internally. (0.12).

Changing lib requirements usually necessitates a version bump, but not sure
how much we should be worried here since the requirements.txt had had 0.12
for some time anyway.

**Comment by dalejung** [comment]
So the minimum supported version is whatever is run internally? i.e. 0.12.0 gets dropped once 0.15.2 is deployed?

**Comment by dalejung** [comment]
It seems like requirements.txt is being used both for minimum deps and deployment manifest, which can be at odds. `zipline` could support `0.12.0` even if some higher version is used in production.

**Comment by twiecki** [comment]
Agreed @dalejung that it's not the best model for the reasons you mention.

**Comment by dalejung** [comment]
ah, it was failing on ta-lib compiled with mismatched numpy versions. Switch to the quantopian binstar since that had 1.8. Not sure if that means we drop numpy 1.7? If not, we need to put up a build for it.

**Comment by twiecki** [comment]
For my money we'd focus on upgrading to `pandas` 0.15 and dropping 0.12 rather than setting up everything to support and test pandas 0.12. We're pretty close to that I think.

**Comment by ehebert** [comment]
I agree, especially with how long 15 takes without the history fix applied.

**Comment by dalejung** [comment]
making zipline performant for 15 and dropping support for 12 aren't related. are we dropping support for 12? 



—

**Comment by ehebert** [comment]
Ah, I had forgotten that we had been doing 15 already because of the
un-pegged pandas install. Mea culpa.

**Comment by twiecki** [comment]
If this is superseded by #488, can we close this?

**Comment by dalejung** [comment]
I would have preferred to get this merged in separately. #488 just had it included so travis would run the tests.

**Comment by twiecki** [comment]
Is this merged?

**Comment by dalejung** [comment]
nope, i see eddie removed it from my history perf PR.

**Comment by ehebert** [comment]
I think it's clear to merge those CI specific patches now. Was just
reducing the surface area so I could get my head around it.

**Comment by twiecki** [comment]
@dalejung Can you rebase and merge with master?

**Comment by dalejung** [comment]
it’s rebased. want me to merge when it pings green?


—

**Comment by twiecki** [comment]
Sounds good.

**Comment by dalejung** [comment]
boo i dont have write access

**Pull request merged**
