### PR TITLE
FIX: Error message for BenchmarkAssetNotAvailableTooLate is wrong

### PR DESCRIPTION
**Pull request by lianga888**
Should be '...does not exist on self.trading_days[-1]...' not
self.trading_days[0]

### CODE REVIEW

**Comment by jbredeche** [comment]
LGTM, thanks!  looks like there are some conflicts now.

**Comment by richafrank** [comment]
FWIW, the standard acronym we've been using is BUG: https://github.com/quantopian/zipline/wiki/Zipline-development-guidelines#commit-messages

**Comment by lianga888** [comment]
Oh oops, i've been using FIX when it doesn't even exist

**Comment by richafrank** [comment]
No worries.  Next time...

**Pull request merged**
