### PR TITLE
plot perf result for backtest

### PR DESCRIPTION
**Pull request by jefforeilly**
for common use

### CODE REVIEW

**Comment by ssanderson** [comment]
@jefforeilly thanks for the PR!  I wonder if something like this might be more appropriate for [PyFolio](https://github.com/quantopian/pyfolio), Zipline's sister project for visualizing algorithm results.  One idea might be to move the visualization logic from here to PyFolio, and then add options to the Zipline CLI to generate PyFolio plots at the end of a backtest.  cc @twiecki

**Comment by twiecki** [comment]
I agree with @ssanderson. This PR would be great if instead of custom plotting code, it would use pyfolio to create the tearsheets.

**Comment by FreddieV4** [comment]
@jefforeilly do you plan on continuing work on this PR?

**Comment by freddiev4** [comment]
Going to close this PR due to inactivity. With comments from Scott and Thomas, I think moving this sort of functionality to pyfolio would be good. 

Feel free to open another PR if this is something you'd like to try working on again.

**Pull request closed without merging**
