### PR TITLE
BUG: reload_symbol_maps should clear the equity_supplementary_maps

### PR DESCRIPTION
**Pull request by llllllllll**

### CODE REVIEW

**Comment by FreddieV4** [comment]
Hey @llllllllll could you give me an example of when this occurs/why we want to clear `equity_supplementary_maps`?

**Comment by llllllllll** [comment]
This is useful when you are are writing to the underlying assets db. After each write you need to clear the internal caches.

**Comment by FreddieV4** [comment]
Ok. I understand that. Do you think this warrants any tests to be added?

**Comment by llllllllll** [comment]
I don't think the tests will add much value because it will not automatically ensure that this actually reloads the cache without tightly depending on the implementation of the asset finder. It's probably fine to omit them for now.

**Pull request merged**
