### PR TITLE
Pass analyze

### PR DESCRIPTION
**Pull request by richafrank**
@elmq0022 , Since https://github.com/quantopian/zipline/pull/818 was facing conflicts and such, I rebased and fixed up your branch.  If this looks right to you, and tests pass, we can merge this one in.

### CODE REVIEW

**Comment by elmq0022** [comment]
It looks great and all the test passed.

I assume the merge has to be done on your side, correct?  Do you want me to
go back and close the issue #801 and pull request #818?

Also, this is my first contribution to an open source project.  Honestly it
has been more of a learning curve than I expected.  Thank you for helping
me get over the hump.

**Comment by richafrank** [comment]
> It looks great and all the test passed. 

Great!

> I assume the merge has to be done on your side, correct? Do you want me to go back and close the issue #801 and pull request #818? 

That's correct.  I can update everything on merging.

> Also, this is my first contribution to an open source project. Honestly it has been more of a learning curve than I expected. Thank you for helping me get over the hump.

And we really appreciate it!  Sorry there's such a curve, but I'm happy to help!  And we're always looking for ways to improve the experience...

**Comment by elmq0022** [comment]
Nah, wasn't that bad. The just more issues than I was expecting, mostly
related to my environment.  There seems to be some dependencies beyond what
the list in the development guide: SQLAlchemy, parameterized-nose, toolz,
and cython to name a few.

If I can get these all resolved and actually run the test suite and build
the docs, things will go better.  In fact, getting this done and updating
the developer guide may be a good next task.

**Comment by richafrank** [comment]
Oh interesting!  I *think* those dependencies should be in requirements.txt or requirements_dev.txt, but definitely let us know if anything is missing or submit an update the guide.

**Pull request merged**
